# Site settings
author: Andrew Echeverria 
title: Flatiron School: Software Engineering BootCamp Blog 
header-img: img/home-bg.png
email: andrew.a.echeverria@gmail.com
copyright_name: Andrew Echeverria 
description: > # this means to ignore newlines until "baseurl:"
  Documenting my journey through becoming a Software Engineer 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aaecheverria96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
